name: batchcircle
description: "BatchCircle: Your College. Your Course. Your Circle."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.0
  image_picker: ^1.0.7
  in_app_purchase: ^3.2.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  
